# Generated by Django 5.1 on 2024-08-27 21:39

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_food_food_id_alter_food_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.UUIDField(default=uuid.UUID('f84d81c1-2bda-4f81-b867-e87c98920cc0'), unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 22, 39, 30, 339343)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.ManyToManyField(blank=True, to='core.food')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
