# Generated by Django 5.1 on 2024-08-24 21:05

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_food_active_alter_food_food_id_alter_food_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.UUIDField(default=uuid.UUID('d4775126-4ea2-4eb3-9886-ed6290a93122')),
        ),
        migrations.AlterField(
            model_name='food',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 22, 5, 7, 723949)),
        ),
    ]
