# Generated by Django 5.1 on 2024-08-25 20:33

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_food_food_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.UUIDField(default=uuid.UUID('65c7b9b0-633b-4350-9356-4c58c0c96668')),
        ),
        migrations.AlterField(
            model_name='food',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 21, 33, 11, 457972)),
        ),
    ]
