# Generated by Django 5.1 on 2024-08-29 22:15

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_food_food_id_alter_food_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.UUIDField(default=uuid.UUID('5c7841cf-c627-46ac-b9da-0b936650029c'), unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 29, 23, 15, 56, 936826)),
        ),
    ]
