# Generated by Django 5.1 on 2024-08-29 22:16

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_food_food_id_alter_food_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.UUIDField(default=uuid.UUID('2b9f6ec7-3e52-4052-8786-ff8fc5fd5cc4'), unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 29, 23, 16, 17, 187321)),
        ),
    ]
