# Generated by Django 5.1 on 2024-08-29 22:16

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_food_food_id_alter_food_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.UUIDField(default=uuid.UUID('4026e116-1c44-49e2-a88c-3b7f4037bdc0'), unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 29, 23, 16, 25, 436317)),
        ),
    ]
